### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by nhutlm22** [NativeVision/starter-kit#38]
I'm trying to run Hello World app on my Android device (version 11) but it gets stuck on the "Initializing AR... " screen and crash app.

**Comment by prattvaidya** [comment]
I was facing the same issue and [these changes](https://github.com/ViroCommunity/starter-kit/pull/39/files) did the trick for me

**Comment by prattvaidya** [comment]
I was facing the same issue and [these changes](https://github.com/ViroCommunity/starter-kit/pull/39/files) did the trick for me
