### ISSUE TITLE
Crashes when start the app on android

### ISSUE THREAD

**Issue by MuhannadSayed** [NativeVision/starter-kit#45]
Hi 

Have Android A10 (low-end model) , trying to run the app on it but it's crashes directly when I start the app ! 

I tried with all updates for packages and OS version and cleaning up the caches and all these stuff but it's still same issue 
No error or log either 

Tried to run it from terminal and from Android studio . 
Any ideas ? 
Thanks

**Comment by asadadams** [comment]
Were you able to solve it. Encountering the same issue

**Comment by asadadams** [comment]
Was able to fix my issue 
In your android/build.gradle ; used 4.0.1 for my gradle plugin

**Comment by robertjcolley** [comment]
Please try the latest starter kit! 😄
