### ISSUE TITLE
Crashes on android just app start

### ISSUE THREAD

**Issue by Tushar321321** [NativeVision/starter-kit#46]
LOG  guncelleme 1 4
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[4], "@viro-community/react-viro").ViroConstants.TRACKING_NORMAL')

**Comment by lutfiblog** [comment]
change import from viroConstants to ViroTrackingStateConstants

and replace with this
  if (state === ViroTrackingStateConstants.TRACKING_NORMAL) {
      setText('Hello World!');
    } else if (state === ViroTrackingStateConstants.TRACKING_UNAVAILABLE) {
      // Handle loss of tracking
    }
