### ISSUE TITLE
Invariant Violation: requireNativeComponent: "VRTText" was not found in the UIManager

### ISSUE THREAD

**Issue by faizii023** [NativeVision/starter-kit#50]
Having this error

**Comment by akhilsanker** [comment]
@faizii023 , have you got any workaround?

Facing the same issue here.

**Comment by aboongm** [comment]
Has this been solved?

**Comment by robertjcolley** [comment]
See #65. Duplicate of issue with Android setup not being "out of the box"

**Comment by iamalinski** [comment]
Facing the same error when following the docs. Any clear way to fix this?
