### ISSUE TITLE
'gflags/gflags.h' file not found on iOS

### ISSUE THREAD

**Issue by patrick-tresp** [NativeVision/starter-kit#51]
Hey there it might be related to another cause, but i just checked out latest repo, installed mode modules, ran `pod install` and getting an import error regarding 'gflags/gflags.h' file not found.

I did see that this repos is using RN version 0.65 and that did not include M1 Chip support. 

Does anyone have a workaround without upgrading to latest RN version? ( i would like to just investigate and play around a bit )  The effort to upgrade rn-version all the way up to .70 seems to be a lot :

https://react-native-community.github.io/upgrade-helper/?from=0.65.1&to=0.70.0

thanks for any advise:

**Comment by robertjcolley** [comment]
Can you check with the latest? I've updated the repo to 0.73.
