### ISSUE TITLE
Android Build: Execution failed for task ':app:checkDebugAarMetadata' Min-SDK 

### ISSUE THREAD

**Issue by NiketanG** [NativeVision/starter-kit#59]
Just cloned the Starter Repo and did a yarn install.
On running the `yarn android` (npx react-native run-android), I am getting a build failed error with the following message
```
The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.appcompat:appcompat:1.4.1.
```

**Comment by luckyscjp** [comment]
I cloned it and install node modules after that, while run on android then it's give an error

Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > **The minCompileSdk (31) specified in a**
     **dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)**
     is greater than this module's **compileSdkVersion (android-30).**
     Dependency: androidx.appcompat:appcompat:1.4.1.

**Comment by lowtianwei** [comment]
solved this by added below code into android/build.gradle

<img width="1426" alt="image" src="https://github.com/ViroCommunity/starter-kit/assets/42953280/c3bf1fbe-1f1a-4178-92da-9ac85dab7811">
