### ISSUE TITLE
error on start running

### ISSUE THREAD

**Issue by ebagsrl** [NativeVision/starter-kit#60]
Hello, after following all the steps and launching the command npx react-native run-android I get the following error. How do I solve? Thank you

`Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at stableHash (D:\REACT NATIVE\starter-kit\node_modules\metro-cache\src\stableHash.js:19:8)
    at Object.getCacheKey (D:\REACT NATIVE\starter-kit\node_modules\metro-transform-worker\src\index.js:593:7)
    at getTransformCacheKey (D:\REACT NATIVE\starter-kit\node_modules\metro\src\DeltaBundler\getTransformCacheKey.js:24:19)
    at new Transformer (D:\REACT NATIVE\starter-kit\node_modules\metro\src\DeltaBundler\Transformer.js:48:9)
    at D:\REACT NATIVE\starter-kit\node_modules\metro\src\Bundler.js:22:29 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}`

**Comment by nikitalokhmachev-ai** [comment]
Same issue here. Were you able to solve it?

**Comment by sascha-trarbach** [comment]
I was able to get it running on Windows through the following steps:

- I used the starter kit from here: 
    - https://github.com/ViroCommunity/starter-kit
- Install Java SDK 11
    - Downloaded from here I picked the latest Java 11 version (11.0.20+8). Also added it to path.
    - https://www.openlogic.com/openjdk-downloads?field_java_parent_version_target_id=406&field_operating_system_target_id=436&field_architecture_target_id=All&field_java_package_target_id=All
- Downgraded to Node 16 through NVM
- Remove node_modules folder and install again.
- I also had to change in this file `android\app\build.gradle`
    
    `implementation "com.facebook.react:react-native:+  // From node_modules` 
    
    to 
    
    `implementation "com.facebook.react:react-native:0.65.1  // From node_modules` 
    
    otherwise the build always crashed for me
- When it was running I was facing this issue here but was easy to solve as mentioned:
    
    https://github.com/ViroCommunity/starter-kit/issues/46

Hope this helps someone.

**Comment by perpetuallight** [comment]
That error looks like it is coming from the Metro Bundler. I would look there. Could be the same race condition that I found [here](https://github.com/facebook/metro/blob/c21daba415ea26511e157f794689caab9abe8236/packages/metro/src/Bundler.js#L62). I noticed that it will fail intermittently too. I think that this is correct behavior though. I added a return to the then clause. But I suspect that assigning the full chain to the variable would have a similar effect.

**Comment by jeetsoni** [comment]
> I was able to get it running on Windows through the following steps:
> 
> * I used the starter kit from here:
>   
>   * https://github.com/ViroCommunity/starter-kit
> * Install Java SDK 11
>   
>   * Downloaded from here I picked the latest Java 11 version (11.0.20+8). Also added it to path.
>   * https://www.openlogic.com/openjdk-downloads?field_java_parent_version_target_id=406&field_operating_system_target_id=436&field_architecture_target_id=All&field_java_package_target_id=All
> * Downgraded to Node 16 through NVM
> * Remove node_modules folder and install again.
> * I also had to change in this file `android\app\build.gradle`
>   `implementation "com.facebook.react:react-native:+  // From node_modules`
>   to
>   `implementation "com.facebook.react:react-native:0.65.1  // From node_modules`
>   otherwise the build always crashed for me
> * When it was running I was facing this issue here but was easy to solve as mentioned:
>   [Crashes on android just app start #46](https://github.com/ViroCommunity/starter-kit/issues/46)
> 
> Hope this helps someone.

This works for me
THANKS
