### ISSUE TITLE
App crashes when using ar on Android device.

### ISSUE THREAD

**Issue by baesunyoung6767** [NativeVision/starter-kit#61]
There was no problem when I built and executed the Android environment for using viroreact in my existing project. 
Afterwards, to run the code in App.js of the starter-kit, I imported only the code into my project and ran it, but there is no error log, and the app keeps forcibly shutting down. 
Can you come up with a solution for this part? Minimum sdk is set. Is there anything else I should do?

**Comment by jeetsoni** [comment]
same issue

**Comment by robertjcolley** [comment]
Hi all, I've got a fix for this on #65. We've had one other user verify that this fixes things as I am currently unable to verify myself (my android device is in the mail). I'll keep this open until I personally verify it, but it would be great if you could try this PR out with an android device and comment on the PR saying that it either works or doesn't!

**Comment by robertjcolley** [comment]
Please try this again with the latest version of NativeVision! I've published a new version https://www.npmjs.com/package/@viro-community/react-viro 2.41.0 this past week that fixes a lot of major issues.
