### ISSUE TITLE
(APK Missing Viro Libs)Android Emulator Not Supported By Viro? 

### ISSUE THREAD

**Issue by perpetuallight** [NativeVision/starter-kit#63]
Sorry to bring this up again, but... [Emulator Not Supported By Viro?](https://github.com/ViroCommunity/starter-kit/issues/32#issuecomment-1001760643)

Google appears to have gone to some trouble creating a [Virtual Scene](https://developers.google.com/ar/develop/java/emulator#create_avd) as the source for the back camera on the [emulator](https://developers.google.com/ar/devices#emulators) to allow AR testing to be done without requiring a physical device.

I could not determine why this option was not supported from the link in the Readme and the old documentation appears to be offline. Is this just a legacy reason? 

For my situation, I unpacked the apk(x86_64) generated from this repo and it appears that none of the viro libraries were included... I am not sure what to make of that. Could I have done something wrong? I followed the instructions and I see that the jettify transforms were generated and selected from. The manifest merger report indicates that they were all accounted for. Not sure why they did not end up in the apk?

System:
    OS: macOS 11.7.9
    CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
    Memory: 81.66 MB / 4.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.22.12 - ~/.nvm/versions/node/v12.22.12/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v12.22.12/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v12.22.12/bin/npm
    Watchman: 2023.09.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: 30, 33
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.65.1 => 0.65.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by perpetuallight** [comment]
I am assuming that if the libraries were included they would be linked without issue and no further "support" would be required to use this with the Android Emulator and a Virtual Scene. Any help in getting this addressed would be greatly appreciated. I also assume this is the correct place for this to be addressed since the react-viro package does not support auto-linking.

**Comment by robertjcolley** [comment]
Hi @perpetuallight, at the moment we do not support the android emulator. You can build and run the starter kit with ViroReact v2.23.1 and React Native 0.73.x, but I was unable to use my webcam as a feed and see the AR Scene when using [this guide](https://developers.google.com/ar/develop/c/emulator).

I am tracking this issue internally and I'm hoping to resolve this soon!
