### ISSUE TITLE
Black screen when build starter-kit on Android device but on iOS still working.

### ISSUE THREAD

**Issue by trong13012001** [NativeVision/starter-kit#70]
When I build starter-kit on Android device.I have configed for android in pull resquest. It did not crash but it had only black screen. But on iOS device still working.
This is my react native info.
![image](https://github.com/NativeVision/starter-kit/assets/105483926/be342483-9f6e-405b-8861-dffad0566709)

**Comment by robertjcolley** [comment]
Is this out of the box? have you made any changes to the starter kit?

**Comment by trong13012001** [comment]
I have solved this problems when you release the lastest version code. Thank U
